### PR TITLE
`help` command does not need any permissions

### PR DESCRIPTION
**Pull request by radtriste**

### CODE REVIEW

**Comment by radtriste** [comment]
@bot help

**Comment by radtriste** [comment]
@bot help

**Comment by radtriste** [comment]
@bot test

**Comment by radtriste** [comment]
@bot help

**Comment by radtriste** [comment]
@bot help

**Comment by radtriste** [comment]
@bot help

**Comment by radtriste** [comment]
@bot help

**Review by spolti — APPROVED** [review]

**Pull request merged**
